### ISSUE TITLE
cannot import qbsolv

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/qbsolv#55]
```
>>> from dwave_qbsolv import QBSolv
     Traceback (most recent call last):
       File "<stdin>", line 1, in <module>
       File "dwave_qbsolv/__init__.py", line 1, in <module>
         from dwave_qbsolv.dimod_wrapper import *
       File "dwave_qbsolv/dimod_wrapper.py", line 3, in <module>
         from dwave_qbsolv.qbsolv import run_qbsolv, ENERGY_IMPACT, SOLUTION_DIVERSITY
     ImportError: No module named qbsolv
```

**Comment by arcondello** [comment]
For now, using the following install instruction seems to fix this issue

```
pip install -r requirements.txt
python setup.py build_ext --inplace
python setup.py install
```

**Comment by arcondello** [comment]
This seems to only happen when using the --prefix flag with setup install.
